name: Build, Test and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Calculate version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set Maven Version
        run: |
          echo "Setting Maven version to ${{ steps.gitversion.outputs.semVer }}"
          mvn versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }}

      - name: Build with Maven
        run: mvn clean verify

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Calculate version with GitVersion
        id: gitversion-publish
        uses: gittools/actions/gitversion/execute@v0.9.14

      - name: Set Maven Version
        run: |
          echo "Setting Maven version to ${{ steps.gitversion-publish.outputs.semVer }}"
          mvn versions:set -DnewVersion=${{ steps.gitversion-publish.outputs.semVer }}

      - name: Publish to GitHub Packages
        run: |
          mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
